name: scrollable_positioned_list_example

publish_to: 'none'

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.13.8'

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.4.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  scrollable_positioned_list:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  built_value_generator: ^8.4.0
  build_runner: ^2.2.0
